# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'YXYNetworkDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YXYNetworkDemo
  pod 'AFNetworking', '~> 3.0'
  pod 'PINCache', '~> 2.1.1'


  target 'YXYNetworkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YXYNetworkDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
